# Generated by Django 5.1.3 on 2024-11-18 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcam', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadedvideo',
            old_name='duration',
            new_name='client_duration',
        ),
        migrations.RenameField(
            model_name='uploadedvideo',
            old_name='video',
            new_name='client_video',
        ),
        migrations.AddField(
            model_name='uploadedvideo',
            name='reference_duration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadedvideo',
            name='reference_video',
            field=models.FileField(default='', upload_to='reference_videos/'),
            preserve_default=False,
        ),
    ]
