# Generated by Django 5.1.2 on 2024-11-09 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter_analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='first_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='voter',
            name='last_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='voter',
            name='party_affiliation',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='voter',
            name='precinct_number',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='voter',
            name='street_name',
            field=models.TextField(),
        ),
    ]
